MvcSf/Models/ProductTableViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcSf.Models
{
    public class ProductTableViewModel
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImageFile { get; set; }
        public byte[] ProductImage { get; set; }
        //public int ResultCount { get; set; }
        public int AlreadyInCart { get; set; }
    }
}

MvcSf/Controllers/ProductTableController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcSf.Models;

namespace MvcSf.Controllers
{
    public class ProductTableController : Controller
    {
        private sfdb db = new sfdb();

        // GET: ProductTable
        //public ActionResult Index(string searchString)
        //{
        //    if (String.IsNullOrEmpty(searchString))
        //    {
        //        return View("IndexNullResult");
        //    }
        //    else
        //    {
        //        var productsForSearch = from p in db.ProductTable.Where(s => s.ProductName.Contains(searchString)) select p;
        //        return View(productsForSearch);
        //    }
        //}

        public ActionResult Index(string searchTerm)
        {
            //var resultCount = (from count in db.ProductTable.Where(c => String.IsNullOrEmpty(searchTerm) || c.ProductName.Contains(searchTerm)) select count).Count();
            //var model = db.ProductTable.ToList();
            int cartCount = getCartAmount();
            int ShoppingCartID = getShoppingCartID();
            var products = db.ProductTable.OrderBy(p => p.ProductName).Where(p => String.IsNullOrEmpty(searchTerm) || p.ProductName.Contains(searchTerm))
                //.Take(10)
                .Select(p => new ProductTableViewModel
                {
                    ProductID = p.ProductID,
                    ProductName = p.ProductName,
                    ProductDescription = p.ProductDescription,
                    Quantity = p.Quantity,
                    Price = p.Price,
                    ImageFile = p.ImageFile,
                    ProductImage = p.ProductImage,
                    AlreadyInCart = (from productAmount in db.ShoppingCartProductTable.Where(a => p.ProductID == a.ProductID && a.ShoppingCartID == ShoppingCartID) select productAmount.Quantity).FirstOrDefault()?? 0

                    //((from cartCount in db.ShoppingCartProductTable.Where(c => p.ProductID == c.ProductID && c.ShoppingCartID == () select cartCount))
                    //ResultCount = resultCount
                });

            //var products = (from p in db.ProductTable where String.IsNullOrEmpty(searchTerm) || p.ProductName.Contains(searchTerm) orderby p.ProductName select new ProductTableViewModel
            //{
            //    ProductID = p.ProductID,
            //    ProductName = p.ProductName,
            //    ProductDescription = p.ProductDescription,
            //    Quantity = p.Quantity,
            //    Price = p.Price
            //}).ToList();
            return View(products);
        }

        [HttpGet]
        public PartialViewResult updateCartNavPartial()
        {
            return PartialView("_LoginPartial", "CustomerShared");
        }

        // GET: ProductTable/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductTable productTable = db.ProductTable.Find(id);
            if (productTable == null)
            {
                return HttpNotFound();
            }
            return View(productTable);
        }

        // GET: ProductTable/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductTable/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,ProductDescription,IsPublished,Quantity,Price,ImageFile,DateCreated,CreatedBy,DateModified,ModifiedBy,ProductImage")] ProductTable productTable)
        {
            if (ModelState.IsValid)
            {
                db.ProductTable.Add(productTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productTable);
        }

        // GET: ProductTable/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductTable productTable = db.ProductTable.Find(id);
            if (productTable == null)
            {
                return HttpNotFound();
            }
            return View(productTable);
        }

        // POST: ProductTable/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,ProductDescription,IsPublished,Quantity,Price,ImageFile,DateCreated,CreatedBy,DateModified,ModifiedBy,ProductImage")] ProductTable productTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productTable);
        }

        // GET: ProductTable/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductTable productTable = db.ProductTable.Find(id);
            if (productTable == null)
            {
                return HttpNotFound();
            }
            return View(productTable);
        }

        // POST: ProductTable/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductTable productTable = db.ProductTable.Find(id);
            OrderProductTable ocpt = (from orderItem in db.OrderProductTable.Where(oi => productTable.ProductID == oi.ProductID) select orderItem).FirstOrDefault();
            ShoppingCartProductTable scpt = (from cartItem in db.ShoppingCartProductTable.Where(ci => productTable.ProductID == ci.ProductID) select cartItem).FirstOrDefault();
            if(scpt != null)
            {
                db.ShoppingCartProductTable.Remove(scpt);
            }
            if (scpt != null)
            {
                db.OrderProductTable.Remove(ocpt);
            }
            db.ProductTable.Remove(productTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public int getCartAmount()
        {
            var userQuery = (from userLinq in db.UserTable.Where(userLinq => String.Equals(userLinq.UserName, System.Web.HttpContext.Current.User.Identity.Name)) select userLinq).FirstOrDefault();
            int i = 0;
            if (userQuery != null)
            {
                var matchCartToUserQuery = (from shoppingCartLinq in db.ShoppingCartTable.Where(s => s.UserID == userQuery.UserID) select shoppingCartLinq).FirstOrDefault();
                if (matchCartToUserQuery != null)
                {
                    var getCartItemFromCart = (from cartItemLinq in db.ShoppingCartProductTable.Where(c => c.ShoppingCartID == matchCartToUserQuery.ShoppingCartID) select cartItemLinq);
                    foreach (var countTheseProducts in (from cartItemLinq in db.ShoppingCartProductTable.Where(c => c.ShoppingCartID == matchCartToUserQuery.ShoppingCartID) select cartItemLinq).ToList())
                    {
                        i = i + countTheseProducts.Quantity.Value;
                    }
                }
            }
            return i;
        }

        public int getShoppingCartID()
        {
            int matchIDToUserQuery;
            try
            {
                int userQuery = (from userLinq in db.UserTable.Where(userLinq => String.Equals(userLinq.UserName, System.Web.HttpContext.Current.User.Identity.Name)) select userLinq.UserID).FirstOrDefault();
                matchIDToUserQuery = (from shoppingCartLinq in db.ShoppingCartTable.Where(s => s.UserID == userQuery) select shoppingCartLinq.ShoppingCartID).FirstOrDefault();
            }
            catch
            {
                matchIDToUserQuery = -1;
            }
            return matchIDToUserQuery;
        }
    }
}

MvcSf/Views/ProductTable/Create.cshtml
@model MvcSf.Models.ProductTable

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/CustomerShared/_CustomerLayout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPublished, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPublished)
                    @Html.ValidationMessageFor(model => model.IsPublished, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageFile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcSf/Views/ProductTable/Delete.cshtml
@model MvcSf.Models.ProductTable

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/CustomerShared/_CustomerLayout.cshtml";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPublished)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageFile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcSf/Views/ProductTable/Details.cshtml
@model MvcSf.Models.ProductTable

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/CustomerShared/_CustomerLayout.cshtml";
}

<div>
    <h4>ProductTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPublished)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageFile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductImage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcSf/Views/ProductTable/Edit.cshtml
@model MvcSf.Models.ProductTable

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/CustomerShared/_CustomerLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPublished, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPublished)
                    @Html.ValidationMessageFor(model => model.IsPublished, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageFile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcSf/Views/ProductTable/Index.cshtml
@model IEnumerable<MvcSf.Models.ProductTableViewModel>
@using Newtonsoft.Json;
@{
    ViewBag.Title = "Search Available Products";
    Layout = "~/Views/CustomerShared/_CustomerLayout.cshtml";
}
<script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Ajax.BeginForm(
                                        new AjaxOptions
                                        {
                                            HttpMethod = "get",
                                            InsertionMode = InsertionMode.Replace,
                                            UpdateTargetId = "productSearchResultList"
                                        }))
{
    <p style="text-align: center"><br />
        <input type="search" name="searchTerm" style="padding-right: 95px; margin-right:20px" />
        <input type="submit" value="search By Name" />
        
    </p>
    
}
<div id="productSearchResultsDescription">it's not working</div>
<br /><br />
<script>
    var modelCount = @Model.Count();
    var resultsDescriptions = document.getElementById("productSearchResultsDescription");
    if(modelCount == 0)
    {
        resultsDescriptions.innerHTML = "Your search returned no results.";
    }
    if(modelCount > 0)
    {
        resultsDescriptions.innerHTML = "Your search returned " + modelCount + " results.";
    }
    @*if(@Model.Count() == 0)
    {
        $('#productSearchResultsDescription').text('<p>    Your search returned no results.</p>');
    }
    else
    {
        $('#productSearchResultsDescription').text('<p>    Your search returned '+ @Model.Count() + ' results.</p>');
    }*@

</script>

<div id="productSearchResultList">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                <strong>Amount Already In Cart</strong>
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Quantity)*@
                <strong>Amount Available</strong>
            </th>
            <th><text><b>Edit | Details | Delete</b></text></th>
            <th><text><b>Add Item To Cart</b></text></th>
        </tr>
        @{
            var productID = 0;
        }
        @foreach (var item in Model)
        {
            productID = item.ProductID;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductImage)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.Price)
                </td>
                <td id="amountInCart-@productID">
                    @Html.DisplayFor(modelItem => item.AlreadyInCart@*, new { @id = ("amountInCart-" + itemCounter + "") }*@)
                    @*@Html.DisplayFor(modelItem => item.AlreadyInCart, new { @id = ("amountInCart-" + itemCounter + "") })*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ProductID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ProductID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ProductID })
                </td>
                <td>
                    @*@@Html.ActionLink("Add Item To Cart", "AddToCart", "ShoppingCartProductTable", new { id = item.ProductID }, null);*@
                    
                    <input id="AddItemToCartButton-@productID" type="button" value="Add Item To Cart" onclick="addToCart(@productID)" />
                        

                    

                </td>
            </tr>
        }
    </table>
</div>


<script type="text/javascript">
    function addToCart(itemNumber) {
        console.log("You clicked the button");

        $.ajax({
            type: 'POST',
            data: { id: itemNumber },
            dataType: 'json',
            url: '@Url.Action("AddToCart", "ShoppingCartProductTable")',
            success: function (newAmount) {
                $('#amountInCart-'+itemNumber).html(newAmount[0]);
            @*$('#SeeCart').html("<a href='ShoppingCartProductTable/Index' style='color: #999999';>View Cart: " + newAmount[1] + "</a>");*@

            $.ajax({
                type: 'GET',
                url: '@Url.Action("updateCartNavPartial", "ProductTable")',
                success:function(partialView) {
                    $('#partialLoginContainer').html(partialView);
                }
            })



            },
            error: function() {
                console.log("Something bad happened");
            }
        });

    };
   


</script>