MvcSf/ViewModels/ConfirmOrderViewModel.cs
using MvcSf.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcSf.ViewModels
{
    public class ConfirmOrderViewModel
    {
        //public AddressTable AddressTable { get; set; }
        //public OrderProductTable OrderProductTable { get; set; }
        //public OrderTable OrderTable { get; set; }
        //public ProductTable ProductTable { get; set; }
        //public ShoppingCartProductTable ShoppingCartProductTable { get; set; }
        //public ShoppingCartTable ShoppingCartTable { get; set; }
        //public StateTable StateTable { get; set; }
        //public StatusTable StatusTable { get; set; }
        //public sysdiagrams sysdiagrams { get; set; }
        //public UserTable UserTable { get; set; }

        public int AddressID { get; set; }
        public int UserID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string UserName { get; set; }
        public string City { get; set; }
        public int StateID { get; set; }
        public String State { get; set; }
        public string Zipcode { get; set; }
        public DateTime DateTime { get; set; }


        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImageFile { get; set; }
        public byte[] ProductImage { get; set; }
        //public int ResultCount { get; set; }
        public int AlreadyInCart { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }
    }
}

MvcSf/Controllers/PlaceOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcSf.Models;
using MvcSf.ViewModels;

namespace MvcSf.Controllers
{
    public class PlaceOrderController : Controller
    {
        private sfdb db = new sfdb();

        // GET: PlaceOrder
        public ActionResult Index()
        {
            var orderTable = db.OrderTable.Include(o => o.AddressTable).Include(o => o.StatusTable).Include(o => o.UserTable);
            return View(orderTable.ToList());
        }

        // GET: PlaceOrder/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderTable orderTable = db.OrderTable.Find(id);
            if (orderTable == null)
            {
                return HttpNotFound();
            }
            return View(orderTable);
        }
        

        // GET: PlaceOrder/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult CreateAddress(int id, [Bind(Include = "Address1, Address2, Address3, City, StateID, ZipCode, IsBilling, IsShipping, DateCreated, CreatedBy, DateModified, ModifiedBy")] AddressTable addressTable)
        //{
        //    ViewBag.AddressID = new SelectList(db.AddressTable, "AddressID", "Address1");
        //    ViewBag.StatusID = new SelectList(db.StatusTable, "StatusID", "StatusDescription");
        //    ViewBag.UserID = new SelectList(db.UserTable, "UserID", "UserName");


        //    if (ModelState.IsValid)
        //    {
        //        addressTable.UserID = id;
        //        db.AddressTable.Add(addressTable);
        //        db.SaveChanges();
        //        return RedirectToAction("ChooseAddress");
        //    }

        //    return View(addressTable);
        //}

        // GET: AddressTable/Create
        public ActionResult CreateAddress()
        {
            ViewBag.StateID = new SelectList(db.StateTable, "StateID", "StateAbbrev");
            ViewBag.UserID = new SelectList(db.UserTable, "UserID", "UserName");
            return View();
        }

        // POST: AddressTable/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAddress([Bind(Include = "Address1,Address2,Address3,City,StateID,ZipCode,IsBilling,IsShipping")] AddressTable addressTable)
        {
            if (ModelState.IsValid)
            {
                var userQuery = (from userLinq in db.UserTable.Where(u => String.Equals(u.UserName, System.Web.HttpContext.Current.User.Identity.Name)) select userLinq).FirstOrDefault();
                addressTable.UserID = userQuery.UserID;
                addressTable.DateCreated = DateTime.Now;
                addressTable.CreatedBy = userQuery.UserName;
                addressTable.DateModified = DateTime.Now;
                addressTable.ModifiedBy = userQuery.UserName;
                db.AddressTable.Add(addressTable);
                db.SaveChanges();
                return RedirectToAction("ChooseAddress");
            }

            ViewBag.StateID = new SelectList(db.StateTable, "StateID", "StateAbbrev", addressTable.StateID);
            ViewBag.UserID = new SelectList(db.UserTable, "UserID", "UserName", addressTable.UserID);
            return View(addressTable);
        }

        public ActionResult ChooseAddress()
        {
            //var addressTable = db.AddressTable.Include(which => which.OrderTable).Include(which => which.UserTable);
            var userQuery = (from userLinq in db.UserTable.Where(userLinq => String.Equals(userLinq.UserName, System.Web.HttpContext.Current.User.Identity.Name)) select userLinq).FirstOrDefault();
            ViewBag.UserID = userQuery.UserID;
            var addressQuery = from addressLinq in db.AddressTable.Where(addressLinq => addressLinq.UserID == userQuery.UserID) select addressLinq;
            return View(addressQuery.ToList());
        }

        public ActionResult ConfirmOrderAddress(int id)
        {
            var addressQuery = (from addressLinq in db.AddressTable.Where(addressLinq => addressLinq.AddressID == id) select addressLinq).FirstOrDefault();
            //var userQuery = (from userLinq in db.UserTable.Where(u => u.UserID == addressQuery.UserID) select userLinq).FirstOrDefault();
            //var cartQuery = (from cartLinq in db.ShoppingCartTable.Where(c => c.UserID == userQuery.UserID) select cartLinq).FirstOrDefault();
            //var itemQuery = (from itemLinq in db.ShoppingCartProductTable.Where(i => i.ShoppingCartID == cartQuery.ShoppingCartID) select itemLinq).ToList();
            return View(addressQuery);
        }

        [HttpGet]
        public ActionResult ConfirmOrderItems()
        {
            var userID = (from userLinq in db.UserTable.Where(userLinq => String.Equals(userLinq.UserName, System.Web.HttpContext.Current.User.Identity.Name)) select userLinq.UserID).FirstOrDefault();
            var cartID = (from cartLinq in db.ShoppingCartTable.Where(c => c.UserID == userID) select cartLinq.ShoppingCartID).FirstOrDefault();
            var itemQuery = (from itemLinq in db.ShoppingCartProductTable.Where(i => i.ShoppingCartID == cartID) select itemLinq).ToList();
            
            return PartialView("ConfirmOrderItems", itemQuery);
        }


        public ActionResult CompleteOrder(int id)
        {
            var userQuery = (from userLinq in db.UserTable.Where(userLinq => String.Equals(userLinq.UserName, System.Web.HttpContext.Current.User.Identity.Name)) select userLinq).FirstOrDefault();
            var matchCartToUserQuery = (from shoppingCartLinq in db.ShoppingCartTable.Where(s => s.UserID == userQuery.UserID) select shoppingCartLinq).FirstOrDefault();
            var matchCartItemToCart = (from cartItemLinq in db.ShoppingCartProductTable.Where(c => c.ShoppingCartID == matchCartToUserQuery.ShoppingCartID) select cartItemLinq);

            decimal totalPriceSum = 0;
            for(int k = 0; k < matchCartItemToCart.Count(); k++)
            {
                totalPriceSum += (decimal)(matchCartItemToCart.ToList()[k].Quantity * matchCartItemToCart.ToList()[k].Price);

            }
            OrderTable ot = new OrderTable
            {
                UserID = userQuery.UserID,
                AddressID = id,
                OrderDate = DateTime.Now,
                //Total = (decimal)matchCartItemToCart.ToList().Sum(x => x.Quantity * x.Price)   can't get this to work FIND OUT WHY. so instead for now I'll use totalPriceSum
                Total = totalPriceSum
            };
            db.OrderTable.Add(ot);



            foreach (var item in matchCartItemToCart)
            {

                OrderProductTable opt = new OrderProductTable
                {
                    OrderID = ot.OrderID,
                    ProductID = item.ProductID,
                    Quantity = item.Quantity,
                    Price = item.Price,
                    DateCreated = DateTime.Now
                };
                db.OrderProductTable.Add(opt);

                var productTemp = (from qualityQualifier in db.ProductTable.Where(QQ => QQ.ProductID == item.ProductID) select qualityQualifier).FirstOrDefault();
                productTemp.Quantity = productTemp.Quantity - item.Quantity;
                if (productTemp.Quantity < 1)
                {
                    db.ProductTable.Remove(productTemp);
                }
                db.ShoppingCartProductTable.Remove(item);
            }

            db.ShoppingCartTable.Remove(matchCartToUserQuery);

            db.SaveChanges();
            return View();
        }


        //Finalizes the order, and then thanks the user for their business.
        /*public ActionResult Thanks()
        {
            var userQuery = (from userLinq in db.UserTable.Where(userLinq => String.Equals(userLinq.UserName, System.Web.HttpContext.Current.User.Identity.Name)) select userLinq).FirstOrDefault();
            var matchCartToUserQuery = (from shoppingCartLinq in db.ShoppingCartTable.Where(s => s.UserID == userQuery.UserID) select shoppingCartLinq).FirstOrDefault();
            var matchCartItemToCart = (from cartItemLinq in db.ShoppingCartProductTable.Where(c => c.ShoppingCartID == matchCartToUserQuery.ShoppingCartID) select cartItemLinq);
            //decimal totalPriceSum = 0;
            //for (int kwant = 0; kwant < matchCartItemToCart.ToList().Count(); kwant++)
            //{
            //    totalPriceSum += (decimal)(matchCartItemToCart.ToList()[kwant].Price);
            //}

            OrderTable ot = new OrderTable
            {
                UserID = userQuery.UserID,
                OrderDate = DateTime.Now,
                StatusID = 1,   //enters first status phase
                Total = matchCartItemToCart.ToList().Sum(x => x.Quantity * x.Price)/*.ToString("$0.00")*/
                //Total = totalPriceSum
            /*};
            db.OrderTable.Add(ot);



            foreach (var item in matchCartItemToCart)
            {

                OrderProductTable opt = new OrderProductTable
                {
                    OrderID = ot.OrderID,
                    ProductID = item.ProductID,
                    Quantity = item.Quantity,
                    Price = item.Price,
                    DateCreated = DateTime.Now
                };
                db.OrderProductTable.Add(opt);

                var productTemp = (from qualityQualifier in db.ProductTable.Where(QQ => QQ.ProductID == item.ProductID) select qualityQualifier).FirstOrDefault();
                productTemp.Quantity = productTemp.Quantity - item.Quantity;

MvcSf/Views/PlaceOrder/ChooseAddress.cshtml
@model IEnumerable<MvcSf.Models.AddressTable>

@{
    ViewBag.Title = "ChooseAddress";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>ChooseAddress</h2>*@

<p>
    @Html.ActionLink("Enter New Billing Address", "CreateAddress", new {id = ViewBag.UserID});
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Address1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsBilling)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsShipping)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateModified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StateTable.StateAbbrev)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserTable.UserName)
        </th>
        <th><text><b>Edit | Details | Delete</b></text></th>
        <th><text><b>Choose this address</b></text></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Address1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address3)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ZipCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsBilling)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsShipping)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateModified)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StateTable.StateAbbrev)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserTable.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AddressID }) |
            @Html.ActionLink("Details", "Details", new { id=item.AddressID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AddressID })
        </td>
        <td>
            @Html.ActionLink("Choose this address", "ConfirmOrderAddress", "PlaceOrder", new { id = item.AddressID }, null);
        </td>
    </tr>
}

</table>

MvcSf/Views/PlaceOrder/ConfirmOrder.cshtml
@model MvcSf.ViewModels.ConfirmOrderViewModel
@using MvcSf.Models;

@{
    ViewBag.Title = "Confirm Order";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ConfirmOrder</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.Address1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.Address2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.Address3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.ZipCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.IsBilling)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.IsShipping)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.DateModified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.ModifiedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.StateTable.StateAbbrev)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressTable.UserTable.UserName)
        </th>
        <th></th>
    </tr>
    @{
        sfdb db = new sfdb();
        var userQuery = (from userLinq in db.UserTable.Where(u => u.UserName == System.Web.HttpContext.Current.User.Identity.Name) select userLinq).FirstOrDefault();
        var addressQuery = (from addressLinq in db.AddressTable.Where(a => a.UserID == userQuery.UserID) select addressLinq).ToList();
    }
    @foreach (var item in addressQuery)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Address1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsBilling)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsShipping)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateModified)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StateTable.StateAbbrev)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserTable.UserName)
            </td>
        </tr>
    }

</table>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateModified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageFile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductTable.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShoppingCartTable.CreatedBy)
        </th>
        <th></th>
    </tr>


    @{
        var shoppingCartQuery = (from shoppingCartLinq in db.ShoppingCartTable.Where(c => c.UserID == userQuery.UserID) select shoppingCartLinq).FirstOrDefault();
        var shoppingCartProductQuery = (from shoppingCartProductLinq in db.ShoppingCartProductTable.Where(ci => ci.ShoppingCartID == shoppingCartQuery.ShoppingCartID) select shoppingCartProductLinq).ToList();
    }
    @foreach (var item in shoppingCartProductQuery)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateModified)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageFile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductTable.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShoppingCartTable.CreatedBy)
            </td>
        </tr>
    }

</table>

Total Price: @ViewBag.Price
<br /><br />
@Html.ActionLink("Complete Order", "CompleteOrder", "PlaceOrder")

MvcSf/Views/PlaceOrder/ConfirmOrderAddress.cshtml
@model MvcSf.Models.AddressTable

@{
    ViewBag.Title = "Confirm Order";
    Layout = "~/Views/CustomerShared/_CustomerLayout.cshtml";
}
<script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
@*<h2>ConfirmOrderAddress</h2>*@

<div style="width: 100%; display: table;">
    <div style="display: table-row">
        <div style="width: 600px; display: table-cell;">
            @*<h4>AddressTable</h4>*@
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Address1)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address1)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Address2)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address2)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Address3)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address3)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.City)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.City)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ZipCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ZipCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsBilling)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsBilling)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsShipping)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsShipping)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateCreated)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateCreated)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CreatedBy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreatedBy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateModified)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateModified)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ModifiedBy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedBy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.StateTable.StateAbbrev)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StateTable.StateAbbrev)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UserTable.UserName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserTable.UserName)
                </dd>

            </dl>
        </div>
        <div id="itemsInYourOrder"style="display: table-cell; border-left: 10px; border-color: #999999">

        </div>
    </div>
</div>

<hr/>
@*<button type="button" id="placeYourOrder929">Place your order</button>*@
@Html.ActionLink("Place Order", "Thanks", "PlaceOrder", new { id = (int)Model.AddressID }, null)
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AddressID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@
<script>
    $.ajax({
        type: 'GET',
        url: '@Url.Action("ConfirmOrderItems", "PlaceOrder")',
        success: function (partialView) {
            $('#itemsInYourOrder').html(partialView);

        }
    })

    @*
    $('#placeYourOrder929').click(function () {
        $.ajax({
            type: 'POST',
            data: { id: cartItemID, quantity: quantInput },
            dataType: 'json',
            url: '@Url.Action("PlaceOrder", "PlaceOrder")',
            success: function (plumbus) {
            });*@
</script>

MvcSf/Views/PlaceOrder/ConfirmOrderItems.cshtml
@model IEnumerable<MvcSf.Models.ShoppingCartProductTable>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateModified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.ImageFile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductTable.ProductName)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.ShoppingCartTable.CreatedBy)
        </th>
        <th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            $@Html.DisplayFor(modelItem => item.Price)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.CreatedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateModified)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedBy)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.ImageFile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductTable.ProductName)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.ShoppingCartTable.CreatedBy)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ShoppingCartProductID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ShoppingCartProductID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ShoppingCartProductID })
        </td>*@
    </tr>
}

</table>

MvcSf/Views/PlaceOrder/Delete.cshtml
@model MvcSf.Models.OrderTable

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressTable.Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressTable.Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusTable.StatusDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusTable.StatusDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>